### ISSUE TITLE
Permissions denied if folders are read only

### ISSUE THREAD

**Issue by hollyallen8** [bdavis222/dot-scanner#22]
density.py line 256

**Comment by hollyallen8** [comment]
We need to print a useful message to the console when there is a PermissionError in this line, e.g.,

try:
    # code that should run
except PermissionError:
  # print useful message about checking permissions
  quit()

**Comment by bdavis222** [comment]
The `saveLifetimeDataFiles` function within `lifetime.py` will also need to be updated with try/except blocks.
